server:
  port: 7073


spring:
  application:
    name: zuul
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 0.1
     ## percentage: 1
      ## https://github.com/apache/incubator-zipkin
  redis:
    host: 3.95.90.26
    port: 6379
    password: 5325#@VeSync
    timeout:  10000

eureka:
  client:
    service-url:
      default-zone: 127.0.0.1:8761/eureka/
zuul:
  routes:
    application:
      service-id: application
      path: /application/**
  
  host:
    connect-timeout-millis: 5000
    socket-timeout-millis: 50000



