server:
  port: 7070


spring:
  application:
    name: service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Hongkong
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/test
eureka:
  client:
    service-url:
      default-zone: 127.0.0.1:8761/eureka/

mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: tk.mapper.model
  configuration:
    map-underscore-to-camel-case: true