server:
  port: 7666



spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liaoyuecai/configuration
          search-paths: cloud



eureka:
  client:
    service-url:
      default-zone: 127.0.0.1:8761/eureka/